const PACKAGES = {
  1: {
    name: 'Chardham Yatra',
    total: 89499,
    route: 'Dehradun - Yamunotri - Gangotri - Kedarnath - Badrinath',
    from: 'Dehradun',
    to: 'Dehradun',
    helipad: 'Dehradun Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'Himalayan heli service Pvt Ltd',
    manager: 'Ajmar Kullu',
    hasReturn: true,
  },
  2: {
    name: 'Do Dham Yatra',
    total: 39999,
    route: 'Dehradun - Kedarnath - Badrinath',
    from: 'Dehradun',
    to: 'Dehradun',
    helipad: 'Dehradun Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'Himalayan heli service Pvt Ltd',
    manager: 'Ajmar Kullu',
    hasReturn: true,
  },
  3: {
    name: 'Dehradun to Kedarnath Yatra - One Way',
    total: 11250,
    route: 'Dehradun - Kedarnath',
    from: 'Dehradun',
    to: 'Kedarnath',
    helipad: 'Dehradun Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'United Helicopters',
    manager: 'Booking Desk',
    hasReturn: false,
  },
  4: {
    name: 'Dehradun to Kedarnath Yatra - Two Way',
    total: 22500,
    route: 'Dehradun - Kedarnath',
    from: 'Dehradun',
    to: 'Kedarnath',
    helipad: 'Dehradun Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'United Helicopters',
    manager: 'Booking Desk',
    hasReturn: true,
  },
  7: {
    name: 'Sersi to Kedarnath Yatra - One Way',
    total: 3043,
    route: 'Sersi - Kedarnath',
    from: 'Sersi',
    to: 'Kedarnath',
    helipad: 'Sersi Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'Arrow Aircraft',
    manager: 'Booking Desk',
    hasReturn: false,
  },
  8: {
    name: 'Sersi to Kedarnath Yatra - Two Way',
    total: 6086,
    route: 'Sersi - Kedarnath',
    from: 'Sersi',
    to: 'Kedarnath',
    helipad: 'Sersi Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'Arrow Aircraft',
    manager: 'Booking Desk',
    hasReturn: true,
  },
  9: {
    name: 'Guptkashi to Kedarnath Yatra - One Way',
    total: 6077,
    route: 'Guptkashi - Kedarnath',
    from: 'Guptkashi',
    to: 'Kedarnath',
    helipad: 'Guptkashi Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'Trans Bharat Aviations',
    manager: 'Booking Desk',
    hasReturn: false,
  },
  10: {
    name: 'Guptkashi to Kedarnath Yatra - Two Way',
    total: 12154,
    route: 'Guptkashi - Kedarnath',
    from: 'Guptkashi',
    to: 'Kedarnath',
    helipad: 'Guptkashi Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'Trans Bharat Aviations',
    manager: 'Booking Desk',
    hasReturn: true,
  },
  11: {
    name: 'Phata to Kedarnath Yatra - One Way',
    total: 4840,
    route: 'Phata - Kedarnath',
    from: 'Phata',
    to: 'Kedarnath',
    helipad: 'Phata Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'United Helicopters',
    manager: 'Booking Desk',
    hasReturn: false,
  },
  12: {
    name: 'Phata to Kedarnath Yatra - Two Way',
    total: 9680,
    route: 'Phata - Kedarnath',
    from: 'Phata',
    to: 'Kedarnath',
    helipad: 'Phata Helipad',
    operator: 'Trans Bharat Aviation',
    merchant: 'United Helicopters',
    manager: 'Booking Desk',
    hasReturn: true,
  },
};

function getPackage(packageId) {
  return PACKAGES[Number(packageId)] || null;
}

module.exports = { PACKAGES, getPackage };
